api:
  # API Address that you want to listen on
  addr: "localhost:3412"

bot:
  # Your bot manager's token gathered from BotFather
  token: "your-bot-token"
  # User id of the people who should have access to this bot
  admins: [682785614]

telegram_bot_api:
  # telegram-bot-api directory which is passed to the
  # running telegram-bot-api instance via "-dir" param
  dir: "/path/to/tg-bot-api-dir"
  # telegram-bot-api's instance host url
  host: "http://localhost:8081"
